demo01/booktest/urls.py
from django.conf.urls import url
from . import views

app_name = 'booktest'

urlpatterns = [
    # url('index/', views.index),
    # url('index/$', views.index),

    url(r'^$', views.index, name='index'),

    url(r'login/$', views.login, name='login'),
    url(r'logout/$', views.logout, name='logout'),

    url(r'list/$', views.list, name='list'),
    url(r'detail/(\d+)/$', views.detail, name='detail'),
    url(r'addbook/$', views.addbook, name='addbook'),
    url(r'addbookhander/$', views.addbookhander, name='addbookhander'),
    url(r'delete/(\d+)/$', views.delete, name='delete'),
    url(r'modifybook/(\d+)/$', views.modifybook, name='modifybook'),
    url(r'modifybookhander/(\d+)/$', views.modifybookhander, name='modifybookhander'),
    url(r'addhero/(\d+)/$', views.addhero, name='addhero'),
    url(r'deletehero/(\d+)/$', views.deletehero, name='deletehero'),
    url(r'modifyhero/(\d+)/$', views.modifyhero, name='modifyhero'),
    url(r'modifyherohander/(\d+)/$', views.modifyherohander, name='modifyherohander'),
    url(r'addherohander/$', views.addherohander, name='addherohander'),
]

demo01/demo01/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booktest/', include('booktest.urls', namespace='booktest'))
]

"""
项目URL
urlpatterns 列表将路由与视图绑定在一起
"""

"""
去除硬编码

1、在应用urls.py添加app_name
2、在项目urls配置文件中 在include中添加命名空间
3、在应用配置文件中给url设置名字
4、在HTML中取出硬编码 {% url '命名空间:url名字' 参数 %}

"""

demo01/booktest/models.py
from django.db import models

# Create your models here.


class Book(models.Model):
    book_title = models.CharField(max_length=20)
    book_pubdate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.book_title


class Hero(models.Model):
    name = models.CharField(max_length=20)
    gender = models.BooleanField()
    content = models.CharField(max_length=50)
    # 外键 第一个参数：关联的表名 第二个参数：删除类型
    book = models.ForeignKey("Book", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def hname(self):
        return self.name
    hname.short_description = "姓名"

    def hsex(self):
        return self.gender
    hsex.short_description = "性别"

    def hcontent(self):
        return self.content
    hcontent.short_description = "绝招"


"""
Django框架MVT模式中M
ORM 对象中的O
需要定义实体类

1、定义模型，继承models.Model
2、配置数据库，默认sqlite
3、将apps.py应用名添加到settings.py的INSTALLED_APPS应用列表中
4、生成迁移文件 python manage.py makemigrations
5、执行迁移 python manage.py migrate

"""

"""
shell命令测试：
进入shell命令： python manage.py shell  不需要运行项目就可以操作数据库
导入类： from booktest.models import *
查找所有行 表名.objects.all()
根据主键查找 表名.objects.get(pk=主键名)
添加对象到数据库 对象.save()
修改对象到数据库 对象.列名=修改的值  对象.save()
删除 对象.delete()

若存在一对多关系： 一方.多方类名全小写_set.all() 可查询相应信息

类名.objects.create(列名=值)  不需要save()
"""

demo01/booktest/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Book,Hero
from django.template import loader
from datetime import timedelta

# Create your views here.


def login(request):
    if request.method == 'GET':
        return render(request, 'booktest/login.html')
    elif request.method == 'POST':
        username = request.POST['username']
        # password = request.POST['password']
        request.session['username'] = username
        # request.session['password'] = password
        request.session.set_expiry(3600)
        # request.session.set_expiry(timedelta(days=5))  报错

        return redirect(reverse('booktest:index'))


def logout(request):
    res = render(request, 'booktest/index.html')
    # res.delete_cookie('username')

    request.session.delete('username')
    # request.session.delete('password')

    return res


def index(request):
    print("请求", request)
    # return HttpResponse("首页")
    # # 1、加载模板
    # indexpage = loader.get_template('booktest/index.html')
    # body = {"username": "ggb"}
    # # 2、使用变量渲染模板
    # result = indexpage.render(body)
    # # 3、返回模板
    # return HttpResponse(result)

    # print(dir(request.COOKIES))
    # print(request.COOKIES.get('username'))
    # return render(request, 'booktest/index.html', {"username": request.COOKIES.get('username')})

    # print(dir(request.session))
    return render(request, 'booktest/index.html', {"username": request.session.get('username')})

    # return render(request, 'booktest/index.html', {"username": "ggb"})


def list(request):
    # return HttpResponse("列表页")
    book = Book.objects.all()
    return render(request, 'booktest/list.html', {'booklist': book})


def detail(request, id):
    # return HttpResponse("详情页"+str(id))

    # book = Book.objects.get(pk=id)
    # return render(request, 'booktest/detail.html', {'book': book})

    try:
        book = Book.objects.get(pk=int(id))
    except:
        # book = get_object_or_404(Book, pk=id)
        book = get_list_or_404(Book, pk=id)
    return render(request, 'booktest/detail.html', {'book': book})


def addbook(request):
    try:
        return render(request, 'booktest/addbook.html', {})
    except:
        return HttpResponse("添加失败")


def addbookhander(request):
    bname = request.POST['bookname']
    # print(bname)
    b = Book()
    b.book_title = bname
    b.save()
    # return HttpResponseRedirect('/booktest/list/', {'booklist': b})
    return HttpResponseRedirect(reverse('booktest:list'), {'booklist': b})


def delete(request, id):
    try:
        Book.objects.get(pk=id).delete()
        book = Book.objects.all()
        # 使用render没有刷新请求URL
        # return render(request, 'booktest/list.html', {'booklist': book})
        # 使用HttpResponseRedirect重定向
        # return HttpResponseRedirect('/booktest/list/', {'booklist': book})
        return HttpResponseRedirect(reverse('booktest:list'), {'booklist': book})
    except:
        return HttpResponse("删除失败")


def modifybook(request, id):
    try:
        b = Book.objects.get(pk=id)
        return render(request, 'booktest/modifybook.html', {"book": b})
    except:
        return HttpResponse("跳转失败")


def modifybookhander(request, id):
    bname = request.POST['bookname']
    b = Book.objects.get(pk=id)
    b.book_title = bname
    b.save()
    # return HttpResponseRedirect('/booktest/list/', {'booklist': b})
    return HttpResponseRedirect(reverse('booktest:list'), {'booklist': b})


def addhero(request, id):
    try:
        # book = Book.objects.get(pk=id)
        return render(request, 'booktest/addhero.html', {"bid":id})
    except:
        return HttpResponse("添加失败")


def deletehero(request, hid):
    try:
        result = Hero.objects.get(pk=hid)
        book = result.book
        result.delete()
        return HttpResponseRedirect('/booktest/detail/'+str(book.id)+'/', {'book': book})
        # return HttpResponseRedirect(reverse('booktest:detail')+str(book.id)+'/', {'book': book})
    except:
        return HttpResponse("添加失败")


def modifyhero(request, id):
    try:
        h = Hero.objects.get(pk=id)
        # print(h.id)
        return render(request, 'booktest/modifyhero.html', {"hero": h})
    except:
        return HttpResponse("跳转失败")


def modifyherohander(request, id):
    hname = request.POST['heroname']
    hgender = request.POST['sex']
    hcontent = request.POST['heroskill']
    bid = request.POST['bid']
    # print(hname, hgender, hcontent, bid)
    b = Book.objects.get(pk=bid)
    h = b.hero_set.get(pk=id)
    h.name = hname
    h.gender = hgender
    h.content = hcontent
    h.book = b
    h.save()
    # print(str(bid))
    # print(reverse('booktest:detail')+str(bid)+'/')
    return HttpResponseRedirect('/booktest/detail/'+str(bid)+'/', {'book': b})
    # return HttpResponseRedirect(reverse('booktest:detail', str(bid)), {'book': b})


def addherohander(request):
    bid = request.POST["bid"]
    hname = request.POST["heroname"]
    hgender = request.POST["sex"]
    hskill = request.POST["heroskill"]
    # print(bid, hname, hgender, hskill)
    # print(hgender, type(hgender))

    book = Book.objects.get(pk=bid)

    h1 = Hero()
    h1.name = hname
    h1.gender = True
    if hgender == "0":
        h1.gender = False
    h1.content = hskill
    h1.book = book
    h1.save()

    return HttpResponseRedirect('/booktest/detail/'+str(bid)+'/', {"book": book})
    # return HttpResponseRedirect(reverse('booktest:detail')+str(bid)+'/', {"book": book})

    # return HttpResponse("提交成功")


"""
视图函数
将函数和路由绑定
"""

"""
使用模板：
1、创建模板文件夹templates
2、配置模板目录 在settings.py中添加 os.path.join(BASE_DIR, 'templates')
3、创建项目模板目录，创建模板

    加载模板 temp = loader.get_template()
    使用变量渲染模板 result = temp.render({})
    返回模板  return HttpResponse(result)

"""

demo01/templates/booktest/addbook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加图书</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="container">
        <h2>添加书籍</h2>
        <form action="{% url 'booktest:addbookhander' %}" method="post">

            书名：<input type="text" name="bookname">
            <input type="submit" value="添加">

        </form>
        <a href="{% url 'booktest:list' %}">返回</a>
    </div>

</body>
</html>

demo01/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加英雄角色</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>添加角色</h2>
        <form action="{% url 'booktest:addherohander' %}" method="post">
            角色名：<input type="text" name="heroname"><br>
            性别：<input type="radio" name="sex" value="1">男
                 <input type="radio" name="sex" value="0">女 <br>
            技能：<input type="text" name="heroskill"><br>
            <input type="hidden" value="{{bid}}" name="bid">

            <input type="submit" value="添加">
        </form>
        <a href="{% url 'booktest:detail' bid %}">返回</a>
    </div>
</body>
</html>

demo01/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>详情页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h2>书名: {{ book.book_title }}</h2>
        <ul>

            {% for hero in book.hero_set.all %}
                <li>{{hero.name}} ------ {{hero.content}}---
                    <a href="{% url 'booktest:deletehero' hero.id %}">删除</a>&nbsp;
                    <a href="{% url 'booktest:modifyhero' hero.id %}">修改</a>
                </li>
            {% empty %}
                <h3>没有英雄</h3>
            {% endfor %}

        </ul>

        <a href="{% url 'booktest:addhero' book.id %}">添加角色</a>


        {# <a href="/booktest/list/">返回</a> #}
        <a href="{% url 'booktest:list' %}">返回</a>

    </div>

</body>
</html>

demo01/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
    {# <link rel="stylesheet" href="/static/css/main.css"> #}

    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">

        {# 单行注释 #}
        {% comment %}
            多行注释
        {% endcomment %}

        {% if username %}
            <h2>欢迎您：<small>{{username}}</small></h2>
            <a href="{% url 'booktest:logout' %}">退出登录</a><br>
            {# 超级链接硬编码 #}
            {#<a href="/booktest/list">进入列表页</a>#}
            {#去除硬编码#}
            <a href=" {% url 'booktest:list' %} ">进入列表页</a>
        {% else %}
            <h2>没有登录,请前往 <a href="{% url 'booktest:login' %}">登录</a></h2>
        {% endif %}

        {# <img src="/static/img/bg1.png" alt="" width="1000px"> #}
        <img src="{% static 'img/bg1.png' %}" alt="" width="1000px"><br>

    </div>

</body>
</html>

demo01/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>列表页</title>
    <link rel="stylesheet" href="/static/css/main.css">
</head>
<body>
    <div class="container">
        <h1>书籍信息</h1>
        <ul>
            {% for book in booklist %}
                {# <li><a href="/booktest/detail/{{book.id}}/">{{ book }}</a> </li> #}
                <li>
                    <a href="{% url 'booktest:detail' book.id %}">{{ book }}</a>
                    <a href="{% url 'booktest:delete' book.id %}">删除</a>
                    <a href="{% url 'booktest:modifybook' book.id %}">修改</a>
                </li>
            {% empty %}
                <h3>没有书籍信息</h3>
            {% endfor %}

        </ul>

        {# <a href="/booktest/">返回首页</a> #}
        <a href="{% url 'booktest:index' %}">返回首页</a>
        <a href="{% url 'booktest:addbook' %}">添加书籍</a>

    </div>

</body>
</html>

demo01/templates/booktest/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
</head>
<body>
    <h2>用户登录</h2>
    <form action="{% url 'booktest:login' %}" method="post">
        用户: <input type="text" name="username" required><br>

        <input type="submit" value="登录">
    </form>
    <a href="{% url 'booktest:index' %}">返回</a>
</body>
</html>

demo01/templates/booktest/modifybook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑书名</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>图书编号：{{book.id}}</h2>
        <form action="{% url 'booktest:modifybookhander' book.id %}" method="post">
            图书名：<input type="text" name="bookname" placeholder="{{book.book_title}}" required>
            <input type="submit" value="保存">
        </form>
        <a href="{% url 'booktest:list' %}">返回</a>
    </div>
</body>
</html>

demo01/templates/booktest/modifyhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑英雄信息</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="container">
        <h2>英雄编号：{{hero.id}}</h2>
        <form action="{% url 'booktest:modifyherohander' hero.id %}" method="post">
            角色名：<input type="text" name="heroname" placeholder="{{hero.name}}" required><br>
            性别：<input type="radio" name="sex" value="1" checked>男
                 <input type="radio" name="sex" value="0">女 <br>
            技能：<input type="text" name="heroskill" placeholder="{{hero.content}}" required><br>
            <input type="hidden" value="{{hero.book.id}}" name="bid">

            <input type="submit" value="添加">
        </form>
        <a href="{% url 'booktest:detail' hero.book.id %}">返回</a>
    </div>

</body>
</html>