Library/BookLibrary/urls.py
from django.conf.urls import url, include
from . import views

app_name = "booklibrary"

urlpatterns = [
    url('^$', views.index, name="index"),
    url('login/(\d+)/$', views.login, name="login"),
    url('manager/$', views.manager, name="manager"),
    url('books/$', views.books, name="books"),
    url('books/add/$', views.books_add, name="books_add"),
    url('books/delete/$', views.books_delete, name="books_delete"),
    url('book/(\d+)/$', views.book_info, name="book_info"),
    url('book/modify/(\d+)/$', views.book_modify, name="book_modify"),

    url('manager/users/$', views.users, name="users"),
    url('manager/user/(\d+)/$', views.manager_user, name="manager_user"),
    url('user/modify/(\d+)/$', views.user_modify, name="user_modify"),
    url('user/delete/(\d+)/$', views.user_delete, name="user_delete"),

    url('regist/$', views.regist, name="regist"),
    url('reader/(\d+)/$', views.reader, name="reader"),
    url('reader_info/(\d+)/$', views.reader_info, name="reader_info"),
    url('reader_modify/(\d+)/$', views.reader_modify, name="reader_modify"),
    url('reader_query/(\d+)/$', views.reader_query, name="reader_query"),
    url('reader_books/(\d+)/(\d+)/$', views.reader_books, name="reader_books"),
    url('reader_historys/(\d+)/$', views.reader_historys, name="reader_historys"),



    # 上传图片
    url('reader_upload/$', views.reader_upload, name="reader_upload"),
    # 富文本编辑
    url('edit/$', views.edit, name="edit"),
    # 发送邮件
    url('mail/$', views.mail, name="mail"),
    url('active/(.*?)/$', views.active, name="active"),
    # Ajax异步刷新
    url('ajax/$', views.ajax, name="ajax"),
    url('ajaxs/$', views.ajaxs, name="ajaxs"),
    url('^ajaxlogin/$', views.ajaxlogin, name="ajaxlogin"),
    url('^checkuser/$', views.checkuser, name="checkuser"),
    url('^verifycode/$', views.verifycode, name="verifycode"),

    url('^echarts/$', views.echarts, name="echarts"),
]

Library/Library/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('booklibrary/', include('BookLibrary.urls', namespace='booklibrary'))
]

Library/BookLibrary/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
# Create your models here.


class Users(models.Model):
    name = models.CharField(max_length=20)
    pwd = models.CharField(max_length=50)
    college = models.CharField(max_length=50)
    num = models.IntegerField()
    email = models.EmailField()
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Books(models.Model):
    name = models.CharField(max_length=30)
    author = models.CharField(max_length=20)
    pub_com = models.CharField(max_length=50)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Borrows(models.Model):
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    date_borrow = models.DateTimeField(auto_now_add=True)
    date_return = models.DateTimeField()
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.book.name+"被"+self.user.name+"借出"


class HotPic(models.Model):
    name = models.CharField(max_length=20)
    pic = models.ImageField(upload_to='hotpic')
    index = models.SmallIntegerField(unique=True)

    def __str__(self):
        return self.name


class MessInfo(models.Model):
    title = models.CharField(max_length=20)
    # 富文本编辑器字段
    message = HTMLField()

    def __str__(self):
        return self.title

Library/BookLibrary/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import *
from datetime import datetime, timedelta
from django.core.mail import send_mail, send_mass_mail
from django.conf import settings

import random, io
from PIL import Image,ImageDraw,ImageFont

from itsdangerous import TimedJSONWebSignatureSerializer as Serializer, SignatureExpired

from django.views.decorators.cache import cache_page

# Create your views here.

@cache_page(60*15)
def index(request):
    # return HttpResponse("你好，世界！")
    messinfo = MessInfo.objects.all()
    hotpics = HotPic.objects.all().order_by('index')
    d = {'manager': 1, 'reader': 0}
    return render(request, 'BookLibrary/index.html', {'t': d, 'hotpics': hotpics, 'messinfo': messinfo})


def login(request, num):
    # print(num, type(num))

    user_dict = {}
    if num == '1':
        user_dict['user'] = "管理员"
        user_dict['load'] = "/booklibrary/login/manager/"
    else:
        user_dict['user'] = "读者"
        user_dict['link2'] = "注册"
        user_dict['load'] = "/booklibrary/login/"+num+'/'
    user_dict['link1'] = "返回"
    user_dict['id'] = int(num)
    if request.method == 'GET':

        return render(request, 'BookLibrary/login.html', {"use": user_dict})
    elif request.method == 'POST':
        name = request.POST['username']
        pwd = request.POST['password']
        request.session['username'] = name
        request.session.set_expiry(3600)
        # print(name, pwd)
        if user_dict['id'] == 1:
            if name == 'admin' and pwd == '123456':
                return redirect(reverse('booklibrary:manager'), {"user": name})
            else:
                return redirect(reverse('booklibrary:login', args=[num]))
        else:
            try:
                u = Users.objects.all().filter(name=name).filter(pwd=pwd)[0]
                return redirect(reverse('booklibrary:reader', args=[u.id]))
            except:
                return redirect(reverse('booklibrary:login', args=[num]))


def manager(request):
    return render(request, 'BookLibrary/manager.html')


def books(request):
    b = Books.objects.all()
    return render(request, 'BookLibrary/manager_books.html', {'books': b})


def books_add(request):
    if request.method == 'GET':
        return render(request, 'BookLibrary/manager_books_add.html')
    elif request.method == 'POST':
        # bid = request.POST['id']
        bname = request.POST['name']
        bauthor = request.POST['author']
        bcompany = request.POST['company']
        bdate = request.POST['date']

        b = Books()
        b.name = bname
        b.author = bauthor
        b.pub_com = bcompany
        b.pub_date = bdate
        b.save()

        return redirect(reverse('booklibrary:books'), {'books': Books.objects.all()})


def books_delete(request):
    if request.method == 'GET':
        return render(request, 'BookLibrary/manager_books_delete.html')
    elif request.method == 'POST':
        bid = request.POST['id']
        # print(bid, type(bid))
        Books.objects.get(pk=bid).delete()
        return redirect(reverse('booklibrary:books'), {'books': Books.objects.all()})


def book_info(request, id):
    b = Books.objects.get(pk=id)
    return render(request, 'BookLibrary/manager_book.html', {'book': b})


def book_modify(request, id):
    b = Books.objects.get(pk=id)
    if request.method == 'GET':
        return render(request, 'BookLibrary/manager_book_modify.html', {'book': b})
    elif request.method == 'POST':
        b.name = request.POST['name']
        b.author = request.POST['author']
        b.pub_com = request.POST['company']
        b.pub_date = request.POST['date']
        b.save()
        return redirect(reverse('booklibrary:book_info', args=[id]), {'book': b})


def users(request):
    u = Users.objects.all()
    return render(request, 'BookLibrary/manager_users.html', {'users': u})


def manager_user(request, id):
    u = Users.objects.get(pk=id)
    return render(request, 'BookLibrary/manager_user.html', {'user': u})


def user_modify(request, id):
    u = Users.objects.get(pk=id)
    if request.method == 'GET':
        return render(request, 'BookLibrary/manager_user_modify.html', {'user': u})
    elif request.method == 'POST':
        u.name = request.POST['username']
        u.pwd = request.POST['password']
        u.college = request.POST['college']
        u.num = request.POST['number']
        u.email = request.POST['email']
        u.save()
        return redirect(reverse('booklibrary:manager_user', args=[id]))


def user_delete(request, id):
    Users.objects.get(pk=id).delete()
    u = Users.objects.all()
    return redirect(reverse('booklibrary:users'), {'users': u})


def regist(request):
    if request.method == 'GET':
        return render(request, 'BookLibrary/regist.html')
    elif request.method == 'POST':
        pwd1 = request.POST['password']
        pwd2 = request.POST['password2']
        if pwd1 == pwd2:
            u = Users()
            u.name = request.POST['username']
            u.pwd = pwd1
            u.college = request.POST['college']
            u.num = request.POST['number']
            u.email = request.POST['email']
            u.save()
            id = Users.objects.get(num=u.num).id

            # 序列化id
            ser = Serializer(settings.SECRET_KEY, 100)
            resultid = ser.dumps({'userid': id}).decode('utf-8')  # 序列化对象转字符串对网址加密
            print(resultid)
            send_mail("用户注册", "<a href='http://127.0.0.1:8000/booklibrary/active/%s'>点我验证</a>" % (resultid, ),
                      settings.DEFAULT_FROM_EMAIL, [u.email, ])
            return redirect(reverse('booklibrary:login', args=[0]))
        else:
            return HttpResponse("两次输入密码不一致")


def reader(request, id):
    u = Users.objects.get(pk=id)
    return render(request, 'BookLibrary/reader.html', {'reader': u})


def reader_info(request, id):
    u = Users.objects.get(pk=id)
    return render(request, 'BookLibrary/reader_info.html', {'user': u})


def reader_modify(request, id):
    u = Users.objects.get(pk=id)
    if request.method == 'GET':
        return render(request, 'BookLibrary/reader_modify.html', {'user': u})
    elif request.method == 'POST':
        u.name = request.POST['username']
        u.pwd = request.POST['password']
        u.college = request.POST['college']
        u.num = request.POST['number']
        u.email = request.POST['email']
        u.save()
        return redirect(reverse('booklibrary:reader', args=[id]))


def reader_query(request, id):
    u = Users.objects.get(pk=id)
    if request.method == 'GET':
        return render(request, 'BookLibrary/reader_query.html', {'user': u})
    elif request.method == 'POST':
        item = request.POST.get('item')
        query = request.POST.get('query')
        # print(item, query)
        if item == 'name':
            b = Books.objects.filter(name=query)
        elif item == 'author':
            b = Books.objects.filter(author=query)
        return render(request, 'BookLibrary/reader_query.html', {'books': b, 'user': u})


def reader_books(request, uid, bid):
    # return HttpResponse("世界你好")
    u = Users.objects.get(pk=uid)
    b = Books.objects.get(pk=bid)
    if request.method == 'GET':
        return render(request, 'BookLibrary/reader_books.html', {'book': b,'user': u})
    elif request.method == 'POST':
        borrow = Borrows.objects.filter(book=b)[0]
        if borrow.status:
            return HttpResponse("此书已借出，请选择其它书籍")
        else:
            lb = borrow
            # print(datetime.now().date())
            # print(datetime.now().date()+timedelta(days=30))
            lb.date_return = datetime.now().date()+timedelta(days=30)
            lb.status = True
            lb.book = b
            lb.user = u
            lb.save()
            return render(request, 'BookLibrary/reader_books.html', {'book': b,'user': u, 'reader': lb})


def reader_historys(request, id):
    print("==================================")
    u = Users.objects.get(pk=id)
    borrow = Borrows.objects.filter(user=u)
    print(u)
    return render(request, 'BookLibrary/reader_borrow.html', {'user': u, 'histroys': borrow})


def reader_upload(request):
    if request.method == 'GET':
        return render(request, 'BookLibrary/reader_upload.html')
    elif request.method == 'POST':
        index = request.POST['index']
        pic = request.FILES['pic']
        pic = HotPic(index=index, pic=pic)
        pic.save()
        return redirect(reverse('booklibrary:index'))


def edit(request):
    if request.method == 'GET':
        return render(request, 'BookLibrary/edit.html')
    elif request.method == 'POST':
        title = request.POST['title']
        mess = request.POST['mess']
        msg = MessInfo(title=title, message=mess)
        msg.save()
        return redirect(reverse('booklibrary:index'))


def mail(request):
    send = settings.DEFAULT_FROM_EMAIL
    receive = ["1451055806@qq.com", "492595085@qq.com"]
    if request.method == 'GET':
        return render(request, 'BookLibrary/email.html', {'send': send, 'receive': receive})
    elif request.method == 'POST':
        title = request.POST['title']
        mess = request.POST['mess']
        try:
            send_mail(title, mess, send, receive)
            print("发送成功")
        except:
            return HttpResponse("发送失败")
        return redirect(reverse('booklibrary:index'))


def active(request, id):
    # 创建序列化对象 100s后过期
    dser = Serializer(settings.SECRET_KEY, 100)
    try:
        # 反序列化ID 将字符串转成对象
        obj = dser.loads(id)
        user = Users.objects.get(pk=obj['userid'])
        user.is_active = True
        user.save()
        return redirect(reverse('booklibrary:login', args=[0]))
    except SignatureExpired as e:
        return HttpResponse("连接失败")


def ajax(request):
    return render(request, 'BookLibrary/ajax.html')

def ajaxs(request):
    if request.method == 'GET':

Library/templates/BookLibrary/ajaxlogin.html
{% extends 'BookLibrary/base.html' %}
{% block title %}登录{% endblock %}
{% block linkjs %}
    <script>

        $(function () {
            $('#username').blur(function () {
                // console.log("+++")
                $.ajax({
                    url: '/booklibrary/checkuser/',
                    type: 'post',
                    data: {
                        "csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val(),
                        "username": $("#username").val()
                    },
                    success: function (data) {
                        console.log("+++")
                        console.log(data)
                        $('#userinfo').text(data);
                    }
                })
            })
            $('#verifycode').click(function () {
                t = new Date()
                this.src = '/booklibrary/verifycode/?t='+t.getTime()
            })
        })

    </script>
{% endblock %}

{% block body %}

    <h2>登录</h2>
    <form action="{% url 'booklibrary:ajaxlogin' %}" method="post">
        {% csrf_token %}
        用户: <input type="text" name="username" id="username"> <span id="userinfo"></span><br>
        密码: <input type="password" name="password" id="password"><br>
        验证码: <input type="text" name="verifycode"><img src="{% url 'booklibrary:verifycode' %}" alt="验证码加载失败" id="verifycode"><br>
        <input type="submit" value="登录">

    </form>

{% endblock %}

Library/templates/BookLibrary/echarts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>图表显示</title>
    <style>
        div{
            float: left;
        }
    </style>
    <script src="https://echarts.baidu.com/examples/vendors/echarts/echarts.min.js"></script>
</head>
<body>

    <div id="main" style="width: 600px;height:400px;"></div>
    <div id="main2" style="width: 600px;height:400px;"></div>
    <div id="main3" style="width: 600px;height:400px;"></div>
    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart1 = echarts.init(document.getElementById('main'));
        var myChart2 = echarts.init(document.getElementById('main2'));

        // 指定图表的配置项和数据
        var option1 = {
            title: {
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: [5, 20, 36, 10, 10, 20]
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
        myChart1.setOption(option1);




        var dataCount = 5e5;
        var data = generateData(dataCount);

        var option2 = {
            title: {
                text: echarts.format.addCommas(dataCount) + ' Data',
                left: 10
            },
            toolbox: {
                feature: {
                    dataZoom: {
                        yAxisIndex: false
                    },
                    saveAsImage: {
                        pixelRatio: 2
                    }
                }
            },
            tooltip: {
                trigger: 'axis',
                axisPointer: {
                    type: 'shadow'
                }
            },
            grid: {
                bottom: 90
            },
            dataZoom: [{
                type: 'inside'
            }, {
                type: 'slider'
            }],
            xAxis: {
                data: data.categoryData,
                silent: false,
                splitLine: {
                    show: false
                },
                splitArea: {
                    show: false
                }
            },
            yAxis: {
                splitArea: {
                    show: false
                }
            },
            series: [{
                type: 'bar',
                data: data.valueData,
                // Set `large` for large data amount
                large: true
            }]
        };

        function generateData(count) {
            var baseValue = Math.random() * 1000;
            var time = +new Date(2011, 0, 1);
            var smallBaseValue;

            function next(idx) {
                smallBaseValue = idx % 30 === 0
                    ? Math.random() * 700
                    : (smallBaseValue + Math.random() * 500 - 250);
                baseValue += Math.random() * 20 - 10;
                return Math.max(
                    0,
                    Math.round(baseValue + smallBaseValue) + 3000
                );
            }

            var categoryData = [];
            var valueData = [];

            for (var i = 0; i < count; i++) {
                categoryData.push(echarts.format.formatTime('yyyy-MM-dd\nhh:mm:ss', time));
                valueData.push(next(i).toFixed(2));
                time += 1000;
            }

            return {
                categoryData: categoryData,
                valueData: valueData
            };
        }
        myChart2.setOption(option2);
    </script>




</body>
</html>

Library/templates/BookLibrary/edit.html
{% extends 'BookLibrary/base.html' %}
{% block title %}富文本编辑{% endblock %}
{% block linkjs %}
    <script src="/static/tiny_mce/tiny_mce.js"></script>
    <script>
        tinyMCE.init({
            'mode':'textareas',
            'theme':'advanced',
            'width':680,
            'height':400
        });
    </script>
{% endblock %}
{% block body %}
    <h2>文本提交</h2>
    <form action="{% url 'booklibrary:edit' %}" method="post">
        {% csrf_token %}
        标题：<input type="text" name="title"><br>
        内容：<textarea name="mess" id="" cols="30" rows="10"></textarea><br>
        <input type="submit" value="提交">
    </form>
{% endblock %}

Library/templates/BookLibrary/email.html
{% extends 'BookLibrary/base.html' %}
{% block title %}邮件发送{% endblock %}
{% block body %}

    <h2>编写邮件</h2>
    <form action="{% url 'booklibrary:mail' %}" method="post">
        {% csrf_token %}
        主题: <input type="text" name="title"><br>
        内容: <textarea name="mess" id="" cols="30" rows="10"></textarea><br>
        发件人: <input type="text" name="email1" readonly value="{{send}}"><br>
        收件人: <input type="text" name="email2" readonly value="{{receive}}"><br>
        <input type="submit" value="发送">
    </form>

{% endblock %}

Library/templates/BookLibrary/manager.html
{% extends 'BookLibrary/base.html' %}
{% block title%} 功能导航 {% endblock %}
{% block link%}
	<a href="{% url 'booklibrary:index' %}"> 注销 [{{ user }}]</a> |
	<a href="{% url 'booklibrary:books' %}"> 图书管理 </a> |
	<a href="{% url 'booklibrary:users' %}"> 用户管理 </a>
{%  endblock%}

Library/templates/BookLibrary/manager_books_add.html
{% extends "BookLibrary/base.html" %}
{% block title %} 增添书目 {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:books' %}"> 返回 </a>
{% endblock %}
{% block body %}
	<h2> 增添书目 </h2>
	{% if error %}
	<div class = error>
	  <strong>Error : </strong> {{error}}
	</div>
	{% endif %}
	<form action="{% url 'booklibrary:books_add' %}" method="post">
        {% csrf_token %}
        <dl>
            {% comment %}
            <dt>ISBN: </dt>
            <dd><input type="text" name="id" size="30"> </dd>
            {% endcomment %}
            <dt>书名:</dt>
            <dd><input type="text" name="name" size="30"> </dd>
            <dt>作者:</dt>
            <dd><input type="text" name="author" size="30"> </dd>
            <dt>出版社:</dt>
            <dd><input type="text" name="company" size="30"> </dd>
            <dt>出版日期:</dt>
            <dd><input type="date" name="date" size="30"> </dd>
        </dl>
        <div class="actions">
            <input type="submit" value="添加">
	    </div>
	</form>

{% endblock %} 

Library/templates/BookLibrary/manager_books_delete.html
{% extends "BookLibrary/base.html" %}
{% block title %} 删除书目 {% endblock %}
{% block link %}
	<a href="{% url 'booklibrary:books' %}"> 返回 </a>
{% endblock %}

{% block body %}
	<h2> 删除书目 </h2>
	{% if error %}
        <div class="error">
            <strong>Errror : </strong> {{error}}
        </div>
	{% endif %}  
	<form action="{% url 'booklibrary:books_delete' %}" method="post">
        {% csrf_token %}
        <dl>
            <dt>请输入书目ISBN:</dt>
            <dd><input type="text" name="id" size="30"> </dd>
        </dl>
        <div class="actions"><input type="submit" value="删除"></div>
    </form>
{% endblock %}

Library/templates/BookLibrary/manager_user_modify.html
{% extends "BookLibrary/base.html" %}
{% block title %} 个人信息修改 {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:manager_user' user.id %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
	<div class="error">
	    <strong>Errror : </strong> {{error}}
	</div>
	{% endif %}  
	<form action="{% url 'booklibrary:user_modify' user.id %}" method="post">
        {% csrf_token %}
	    <dl>
            <dt>用户名:</dt>
            <dd><input type="text" name="username" size="30" value="{{user.name}}"> </dd>
            <dt>请输入新密码(不输入就是不修改):</dt>
            <dd><input type="password" name="password" size="30"> </dd>
            <dt>学院:</dt>
            <dd><input type="text" name="college" size="30" value="{{user.college}}"> </dd>
            <dt>学号:</dt>
            <dd><input type="number" name="number" size="30" value="{{user.num}}"> </dd>
            <dt>邮箱:</dt>
            <dd><input type="email" name="email" size="30" value="{{user.email}}"> </dd>
	    </dl>
	    <div class="actions"><input type="submit" value="确定"></div>
	</form>

{% endblock %}

Library/templates/BookLibrary/reader_books.html
{% extends "BookLibrary/base.html" %}

{% block title %} 书目信息 {% endblock %}
{% block link %}
	{% if book %}
	    <a href="{% url 'booklibrary:reader' user.id %}"> 返回 </a>
	{% endif %}
{% endblock %}

{% block body %}
	{% if error %}
        <div class=error>
            <strong>Errror : </strong> {{error}}
        </div>
	{% endif %}
	<h2> 书目信息 </h2>
	{% if book %}
        <li> ISBN            	{{book.id}} </li>
        <li> 书名        		{{book.name}} </li>
        <li> 作者        		{{book.author}} </li>
        <li> 出版社     	{{book.pub_com}} </li>
        <li> 出版日期   	{{book.pub_date|date:"Y-m-d"}} </li>
	{% endif %}
	<div>
	    <h2 > 借阅信息 </h2>
	    {% if reader  %}
            <li> 借阅者姓名 {{user.name}}</li>
            <li> 借阅日期  {{reader.date_borrow|date:"Y-m-d"}}</li>
            <li> 还书日期  {{reader.date_return|date:"Y-m-d"}}</li>
	    {% else %}
	        <li> 无 </li>
	    {% endif %}

    </div>
    <form action="{% url 'booklibrary:reader_books' user.id book.id %}" method="post">
        {% csrf_token %}
        <div class="actions">
            <input type="submit" value="借阅">
        </div>
    </form>
{% endblock %}

Library/templates/BookLibrary/reader_query.html
{% extends "BookLibrary/base.html" %}
{% block title%} 查询  {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:reader' user.id %}"> 返回 </a>
{% endblock %}
{% block body %}
	<h2> 查询 </h2> 
	{% if error %}
        <div class="error">
            <strong>Errror : </strong> {{error}}
        </div>
	{% endif %}  
    <div class="actions">

	    <form action="{% url 'booklibrary:reader_query' user.id %}" method="post">
            {% csrf_token %}
            <dd>
                <select name="item">
                    <option value="name"> 书名 </option>
                    <option value="author"> 作者 </option>
                </select>
                <input type="text" name="query" size="80">
                <input type="submit" value="查询">
            </dd>
	    </form>
	</div>
	{% if books %}
        <table width="600" border="1" align="center">
            <tr>
                <th align="center"> ISBN </th>
                <th align="center"> 书名 </th>
                <th align="center"> 作者</th>
                <th align="center"> 出版商 </th>
                <th align="center"> 出版时间 </th>
                <th align="center"> 查看信息 </th>
            </tr>
            {% for book in books %}
            <tr>
                <th align="center"> {{book.id}}</th>
                <th align="center"> {{book.name}} </th>
                <th align="center"> {{book.author}}</th>
                <th align="center"> {{book.pub_com}} </th>
                <th align="center"> {{book.pub_date|date:"Y-m-d"}}</th>
                <th align="center"> <a href="{% url 'booklibrary:reader_books' user.id book.id %}"> 点击进入 </a> </th>
            </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

Library/templates/BookLibrary/reader_upload.html
{% extends 'BookLIbrary/base.html' %}
{% block title %}上传图片{% endblock %}
<body>
    {% block link %}<a href="{% url 'booklibrary:index' %}">返回</a>| 上传图片{% endblock %}
    {% block body %}
        <form action="{% url 'booklibrary:reader_upload' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            编号: <input type="text" name="index"><br>
            上传图片: <input type="file" name="pic"><br>
            <input type="submit" value="上传">
        </form>
    {% endblock %}
</body>
</html>

Library/templates/BookLibrary/regist.html
{% extends "BookLibrary/base.html" %}
{% block title %} 注册 {% endblock %}
{% block link %} 
	<a href="{% url 'booklibrary:login' 0 %}"> 返回 </a>
{% endblock %}
{% block body %}
	{% if error %}
        <div class=error>
            <strong>Errror : </strong> {{error}}
        </div>
	{% endif %}  
	<form action="{% url 'booklibrary:regist' %}" method="post">
        {% csrf_token %}
        <dl>
            <dt>用户名:</dt>
            <dd><input type="text" name="username" size="30" required> </dd>
            <dt>密码:</dt>
            <dd><input type="password" name="password" size="30" required> </dd>
            <dt>密码<small>(重复)</small>:	</dt>
            <dd><input type="password" name="password2" size="30" required> </dd>
            <dt>学院:</dt>
            <dd><input type="text" name="college" size="30"> </dd>
            <dt>学号:</dt>
            <dd><input type="number" name="number" size="30" required> </dd>
            <dt>邮箱:</dt>
            <dd><input type="email" name="email" size="30" required> </dd>
	    </dl>
	  <div class="actions"><input type="submit" value="注册"></div>
	</form>

{% endblock %}