demo02/demo02/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('polls/', include('polls.urls', namespace='polls'))
]

demo02/polls/urls.py
from django.conf.urls import url
from . import views

app_name = "polls"

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'vote/(\d+)/$', views.vote, name="vote"),
    url(r'detail/$', views.detail, name="detail"),
    url(r'result/(\d+)/$', views.result, name="result"),

    url(r'addquestion/$', views.addquestion, name='addquestion'),
    url(r'addquestionhander/$', views.addquestionhander, name='addquestionhander'),
    url(r'deletequestion/(\d+)/$', views.deletequestion, name='deletequestion'),
    url(r'modifyquestion/(\d+)/$', views.modifyquestion, name='modifyquestion'),
    url(r'modifyquestionhander/(\d+)/$', views.modifyquestionhander, name='modifyquestionhander'),

    url(r'votemanage/(\d+)/$', views.votemanage, name='votemanage'),
    url(r'addchoice/(\d+)/$', views.addchoice, name='addchoice'),
    url(r'addchoicehander/$', views.addchoicehander, name='addchoicehander'),
    url(r'deletechoice/(\d+)/$', views.deletechoice, name='deletechoice'),
    url(r'modifychoice/(\d+)/$', views.modifychoice, name='modifychoice'),
    url(r'modifychoicehander/(\d+)/$', views.modifychoicehander, name='modifychoicehander'),

]

demo02/polls/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    text = models.CharField(max_length=50)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

    def desctext(self):
        return self.text
    desctext.short_description = '问题描述'


class Select(models.Model):
    item = models.CharField(max_length=20)
    vote = models.IntegerField(default=0)
    question = models.ForeignKey('Question', on_delete=models.CASCADE)

    def __str__(self):
        return self.item

    def choice(self):
        return self.item
    choice.short_description = '问题选项'

    def votes(self):
        return self.vote
    votes.short_description = '投票数'

demo02/polls/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Select

# Create your views here.


def index(request):
    # return HttpResponse("index")
    l = Question.objects.all()
    return render(request, 'polls/index.html', {'ql': l})


def vote(request, id):
    q = Question.objects.get(pk=id)
    return render(request, 'polls/vote.html', {'qs':q, 'qid':id})


def detail(request):
    if 'vote' in request.POST:
        vid = request.POST['vote']
        qid = request.POST['qid']
        # print(vid, type(vid))
        if isinstance(vid, str):
            s = Select.objects.get(pk=vid)
            # print(s.vote, type(s.vote))
            s.vote += 1
            s.save()
            q = Question.objects.get(pk=qid)
            return HttpResponseRedirect('/polls/result/'+str(q.id)+'/', {})
        else:
            return HttpResponse("还没有投票")
    else:
        return HttpResponse("还没有选项信息")


def result(request, id):
    q = Question.objects.get(pk=id)
    return render(request, "polls/result.html", {'qs':q})


def addquestion(request):
    return render(request, 'polls/addquestion.html', {})


def addquestionhander(request):
    title = request.POST['title']
    print(title)
    q = Question()
    q.text = title
    q.save()
    return HttpResponseRedirect('/polls/', {'ql', Question.objects.all()})


def deletequestion(request, id):
    Question.objects.get(pk=id).delete()
    l = Question.objects.all()
    return HttpResponseRedirect('/polls/', {'ql': l})


def modifyquestion(request, id):
    q = Question.objects.get(pk=id)
    return render(request, 'polls/modifyquestion.html', {'qt': q})


def modifyquestionhander(request, id):
    qt = Question.objects.get(pk=id)
    qt.text = request.POST['title']
    qt.save()
    l = Question.objects.all()
    return HttpResponseRedirect('/polls/', {'ql': l})


def votemanage(request, id):
    q = Question.objects.get(pk=id)
    s = q.select_set.all()
    return render(request, 'polls/votemanage.html', {'question': q, 'sl': s})


def addchoice(request, id):
    q = Question.objects.get(pk=id)
    return render(request, 'polls/addchoice.html', {'qs': q})


def addchoicehander(request):
    q = Question.objects.get(pk=request.POST['qid'])
    sl = q.select_set.all()
    s = Select()
    s.item = request.POST['item']
    s.vote = request.POST['vote']
    s.question = q
    s.save()
    return HttpResponseRedirect('polls/votemanage/'+str(q.id)+'/', {'question': q, 'sl': sl})


def deletechoice(request, id):
    l = Select.objects.get(pk=id)
    q = l.question
    l.delete()
    sl = q.select_set.all()
    return HttpResponseRedirect('polls/votemanage/'+str(q.id)+'/', {'question': q, 'sl': sl})


def modifychoice(request, id):
    sl = Select.objects.get(pk=id)
    q = sl.question
    return render(request, 'polls/modifychoice.html', {'question': q, 'sl': sl})


def modifychoicehander(request, id):
    sl = Select.objects.get(pk=id)
    sl.item = request.POST['item']
    sl.vote = request.POST['vote']
    sl.save()
    q = sl.question
    return HttpResponseRedirect('/polls/votemanage/'+str(q.id)+'/', {'question': q, 'sl': sl})

demo02/templates/polls/addchoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加投票选项</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>添加选项</h2>
        <form action="{% url 'polls:addchoicehander' %}" method="post">
            {% csrf_token %}
            选项名称：<input type="text" name="item" required><br>
            投票数：<input type="number" name="vote" required><br>
            <input type="hidden" name="qid" value="{{qs.id}}">
            <input type="submit" value="添加">
        </form>
        <a href="{% url 'polls:votemanage' qs.id %}">返回</a>
    </div>
</body>
</html>

demo02/templates/polls/addquestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加话题</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>热门话题添加</h2>
        <form action="{% url 'polls:addquestionhander' %}" method="post">
            {% csrf_token %}
            标题：<input type="text" name="title" required>
            <input type="submit" value="添加">
        </form>
        <a href="{% url 'polls:index' %}">返回</a>
    </div>
</body>
</html>

demo02/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票详情</title>
    {# <link rel="stylesheet" href="/static/css/main.css"> #}
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>问题：{{qs.text}}</h2>
        {% for s in qs.select_set.all %}
            <li>{{s.item}}: {{s.vote}}</li>
        {% empty %}
            还没有投票
        {% endfor %}
        <a href="{% url 'polls:index' %}">返回话题首页</a>
    </div>
</body>
</html>

demo02/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>问题</title>
    {# <link rel="stylesheet" href="/static/css/main.css"> #}
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>热门问题列表</h2>
        <a href="{% url 'polls:addquestion' %}">添加问题</a>
        <ul>
            {% for l in ql %}
                {# <li><a href="/polls/vote/{{l.id}}/">{{l.text}}</a></li> #}
                <li>
                    {{forloop.counter}} <a href="{% url 'polls:vote' l.id %}">{{l.text}}</a>
                    <a href="{% url 'polls:deletequestion' l.id %}">删除</a>
                    <a href="{% url 'polls:modifyquestion' l.id %}">修改</a>
                </li>
            {% empty %}
                <h3>还没有话题呦</h3>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

demo02/templates/polls/modifychoice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改选项信息</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>编辑选项</h2>
        <form action="{% url 'polls:modifychoicehander' sl.id %}" method="post">
            {% csrf_token %}
            选项：<input type="text" name="item" placeholder="{{sl.item}}" required>
            票数：<input type="number" name="vote" placeholder="{{sl.vote}}" required>
            <input type="submit" value="保存">
        </form>
        <a href="{% url 'polls:votemanage' question.id %}">返回</a>
    </div>
</body>
</html>

demo02/templates/polls/modifyquestion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改话题名称</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="container">
        <h2>话题修改</h2>
        <form action="{% url 'polls:modifyquestionhander' qt.id %}" method="post">
            {% csrf_token %}
            标题：<input type="text" name="title" required placeholder="{{qt.text}}">
            <input type="submit" value="保存">
        </form>
        <a href="{% url 'polls:index' %}">返回</a>
    </div>

</body>
</html>

demo02/templates/polls/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票详情</title>
    {# <link rel="stylesheet" href="/static/css/main.css"> #}
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>问题：{{qs.text}}</h2>
        {% for s in qs.select_set.all %}
            <li>{{s.item}}: {{s.vote}}</li>
        {% empty %}
            还没有投票
        {% endfor %}
        <a href="{% url 'polls:index' %}">返回话题首页</a>
    </div>
</body>
</html>

demo02/templates/polls/vote.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票页</title>
    {# <link rel="stylesheet" href="/static/css/main.css"> #}
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
        <h2>问题：{{qs.text}}</h2>
        <a href="{% url 'polls:votemanage' qid %}">投票管理</a>
        <!--{# <form action="/polls/detail/" method="post"> #}-->
        <form action="{% url 'polls:detail' %}" method="post">
            <ul>
                {# 跨站请求伪造保护，一般用在表单post请求中 #}
                {% csrf_token %}
                {% for i in qs.select_set.all %}
                <li>
                    <input type="radio" name="vote" value="{{i.id}}" required>{{i.item}}
                </li>
                {% empty %}
                    <h3>没有选项</h3>
                {% endfor %}
            </ul>
            <input type="hidden" value="{{qid}}" name="qid">
            <input type="submit" value="投票">
        </form>
        <a href="{% url 'polls:index' %}">返回</a>
    </div>

</body>
</html>

demo02/templates/polls/votemanage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>投票管理</title>
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>

    <div class="container">
        <h2>话题：{{question.text}}</h2>
        <a href="{% url 'polls:addchoice' question.id %}">添加投票选项</a>
        <ul>
            {% for l in sl %}
                <li>
                    {{l}}
                    <a href="{% url 'polls:deletechoice' l.id %}">删除</a>
                    <a href="{% url 'polls:modifychoice' l.id %}">修改</a>
                </li>
            {% empty %}
                <h3>还没有选项</h3>
            {% endfor %}
        </ul>
        <a href="{% url 'polls:vote' question.id  %}">返回</a>
    </div>

</body>
</html>